vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        options:
            uri_prefix: /images/options
            upload_destination: '%kernel.project_dir%/public/images/options'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        mailTypes:
            uri_prefix: /images/mailTypes
            upload_destination: '%kernel.project_dir%/public/images/mailTypes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        bookbinding:
            uri_prefix: /images/bookbinding
            upload_destination: '%kernel.project_dir%/public/images/bookbinding'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
